name: Bug Report
description: Create a report to help us improve
title: 'Bug: '
labels: bug

body:
  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 请简要描述你遇到的问题。
    validations:
      required: false

  - type: textarea
    id: error
    attributes:
      label: 报错信息
      description: 请将完整的报错信息粘贴到此处。
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: 版本信息
      description: 请粘贴 ``import histcite; histcite.show_versions()`` 的结果。
    validations:
      required: true

  - type: dropdown
    id: source
    attributes:
      label: 使用数据源
      multiple: false
      options:
        - Web of Science
        - Scopus
        - CSSCI
    validations:
      required: true

  - type: textarea
    id: dataset
    attributes:
      label: 使用数据集
      description: 请上传一份能复现bug的数据集。
    validations:
      required: false
