name: Publish Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install pdoc
      - run: pdoc histcite -d google -e histcite=https://github.com/doublessay/histcite-python/blob/main/histcite/ -o ./docs --no-show-source
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
